-- Customize Treesitter

---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "vim",
      -- add more arguments for adding more treesitter parsers
      "bash",
      "comment",
      "cpp",
      "c",
      "css",
      "csv",
      "diff",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "graphql",
      "helm",
      "html",
      "htmldjango",
      "http",
      "ini",
      "java",
      "javascript",
      "jinja",
      "jinja_inline",
      "json",
      "json5",
      "just",
      "mermaid",
      "nginx",
      "passwd",
      "python",
      "query",
      "regex",
      "rust",
      "sql",
      "ssh_config",
      "terraform",
      "toml",
      "typescript",
      "xml",
      "yaml",
    },
  },
}
